### ISSUE TITLE
app-editors/textadept fetching failing

### ISSUE THREAD

**Issue by ghost** [fusion809/fusion809-overlay#2]
Saving to: ‘/var/cache/portage/distfiles/bombay.zip’

     0K ..                                                    100% 5.20M=0s

2018-04-23 16:36:06 (5.20 MB/s) - ‘/var/cache/portage/distfiles/bombay.zip’ saved [2209/2209]

!!! Fetched file: bombay.zip VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      2209
!!! Expected: 2211
Refetching... File renamed to '/var/cache/portage/distfiles/bombay.zip._checksum_failure_.voNmLQ'

--2018-04-23 16:36:06--  http://foicica.com/hg/bombay/archive/tip.zip
Resolving foicica.com... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘foicica.com’
!!! Couldn't download 'bombay.zip'. Aborting.

**Comment by fusion809** [comment]
Should be fixed now (in 0e037e6), thanks for reporting.
