### ISSUE TITLE
atom-bin-1.27.0_beta1 Manifest is incorrect

### ISSUE THREAD

**Issue by ghost** [fusion809/fusion809-overlay#3]
!!! Fetched file: atom-beta-amd64-1.27.0-beta1.tar.gz VERIFY FAILED!
!!! Reason: Insufficient data for checksum verification
!!! Got:
!!! Expected: BLAKE2B BLAKE2S MD5 RMD160 SHA1 SHA256 SHA3_256 SHA3_512 SHA512 WHIRLPOOL

**Comment by fusion809** [comment]
Ah that may have been true with earlier commits but I just deleted atom-beta-amd64-1.27.0-beta1.tar.gz from /usr/portage/distfiles, redownloaded and re-manifested it and there's no differences to commit. I suggest you do another git pull and re-try.

**Comment by fusion809** [comment]
Should I mark this issue as closed?

**Comment by ghost** [comment]
yes.
