### ISSUE TITLE
app-editors/vim issues

### ISSUE THREAD

**Issue by ghost** [fusion809/fusion809-overlay#4]
vim, gvim also has a weird name ebuilds which results in following problem:

These are the packages that would be merged, in order:
 
Calculating dependencies -
Invalid ebuild name: /var/git/meta-repo/kits/editors-kit/app-editors/gvim/gvim-.ebuild
 \
Invalid ebuild name: /var/git/meta-repo/kits/editors-kit/app-editors/vim/vim-.ebuild
 /
Invalid ebuild name: /var/git/meta-repo/kits/editors-kit/app-editors/vim-core/vim-core-.ebuild

**Comment by ghost** [comment]
other than that, fetching failing
[ebuild     U  ]  app-editors/vim-core-8.1.0258::editors-kit [8.1.0254::editors-kit] USE="acl nls -minimal" 0 KiBTotal: 3 packages (3 upgrades), Size of downloads: 0 KiBWould you like to merge these packages? [Yes/No] >>> Verifying ebuild manifests>>> Emerging (1 of 3) app-editors/vim-core-8.1.0258::editors-kit
 * Fetching files in the background.
 * To view fetch progress, run in another terminal:
 * tail -f /var/log/emerge-fetch.log
!!! Fetched file: vim-8.1.0258.tar.gz VERIFY FAILED!
!!! Reason: Insufficient data for checksum verification
!!! Got:      
!!! Expected: BLAKE2B BLAKE2S MD5 RMD160 SHA1 SHA256 SHA3_256 SHA3_512 SHA512 WHIRLPOOL
 * Fetch failed for 'app-editors/vim-core-8.1.0258', Log file:
 *  '/var/tmp/portage/app-editors/vim-core-8.1.0258/temp/build.log'>>> Failed to emerge app-editors/vim-core-8.1.0258, Log file:>>>  '/var/tmp/portage/app-editors/vim-core-8.1.0258/temp/build.log' * Messages for package app-editors/vim-core-8.1.0258: * Fetch failed for 'app-editors/vim-core-8.1.0258', Log file:
 *  '/var/tmp/portage/app-editors/vim-core-8.1.0258/temp/build.log'

**Comment by fusion809** [comment]
Hopefully this latest commit fixes things. Sorry, one day I did something silly and tried updating my Vim packages from a chroot into Gentoo from Void. For some reason I've found there's no net when chrooting from Void into a user account (root account does have net, however), but chrooting from other distros doesn't seem to have this problem.

**Comment by fusion809** [comment]
I've built the packages on my Gentoo system now so it seems all is well.

**Comment by ghost** [comment]
thanks

**Comment by fogti** [comment]
@fusion809 The commit https://github.com/fusion809/fusion809-overlay/commit/6b4def7b3cd600ce920f47a4adea057b2b6e3f16 reintroduced this issue.
